version: '3.4'

services:
  smartcloud:
    image: andreigavrilregistry.azurecr.io/smartcloud
    container_name: smartcloud
    build: 
      context: .
      dockerfile: SmartCloud/Dockerfile
    volumes:
        - andreifileshare  


  microserviceclass:
    image: andreigavrilregistry.azurecr.io/microserviceclass
    container_name: microserviceclass
    build:
      context: .
      dockerfile: Microserviciu1/Dockerfile


  microservicestudent:
    image: andreigavrilregistry.azurecr.io/microservicestudent
    container_name: microservicestudent
    build: 
      context: .
      dockerfile: Microserviciu2/Dockerfile
   
volumes:
 mydata:
  driver: azure_file
  driver_opts:
   share_name: andreifileshare
   storage_account_name: andreigavrilstorage
   storageAccountKey: SXXx8+NzSoz3+CwCIRHga4Ch7RwgZikMgRXbJEanPwIbeD8j8VHrbJtVU2GFjNbWkQdNi9rA63SYZTQrktRnxw==
    

