version: '3.4'

services:
  smartcloud:
    image: ${DOCKER_REGISTRY-}smartcloud
    build:
      context: .
      dockerfile: SmartCloud/Dockerfile

  microserviceclass:
    image: ${DOCKER_REGISTRY-}microserviceclass
    build:
      context: .
      dockerfile: Microserviciu1/Dockerfile


  microservicestudent:
    image: ${DOCKER_REGISTRY-}microservicestudent
    build:
      context: .
      dockerfile: Microserviciu2/Dockerfile

